USE [warehouse_management]
GO

/****** Object:  Table [dbo].[types]    Script Date: 6/25/2021 11:52:45 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[types](
	[id] [uniqueidentifier] NOT NULL,
	[name] [nvarchar](10) NOT NULL,
	[unit] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_id] PRIMARY KEY NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_types_name_unit] UNIQUE NONCLUSTERED 
(
	[name] ASC,
	[unit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[types] ADD  DEFAULT (newid()) FOR [id]
GO


